// <auto-generated />
using System;
using EF_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_1.Migrations
{
    [DbContext(typeof(addDbContext))]
    [Migration("20260218113318_94")]
    partial class _94
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_1.Model.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DurationinMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationinMonths = 6,
                            Fees = 25600m,
                            Title = ".NET Core"
                        },
                        new
                        {
                            Id = 2,
                            DurationinMonths = 3,
                            Fees = 15500m,
                            Title = "LINQ"
                        });
                });

            modelBuilder.Entity("EF_1.Model.student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("studentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("studentId");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "het@gmail.com",
                            Name = "Het"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jeet@gmail.com",
                            Name = "Jeet"
                        });
                });

            modelBuilder.Entity("EF_1.Model.trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("trainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("trainerId");

                    b.ToTable("trainer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperienceYears = 6,
                            Name = "Mewada"
                        },
                        new
                        {
                            Id = 2,
                            ExperienceYears = 4,
                            Name = "Raj"
                        });
                });

            modelBuilder.Entity("EF_1.Model.Course", b =>
                {
                    b.HasOne("EF_1.Model.Course", null)
                        .WithMany("Courses")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("EF_1.Model.student", b =>
                {
                    b.HasOne("EF_1.Model.student", null)
                        .WithMany("students")
                        .HasForeignKey("studentId");
                });

            modelBuilder.Entity("EF_1.Model.trainer", b =>
                {
                    b.HasOne("EF_1.Model.trainer", null)
                        .WithMany("trainers")
                        .HasForeignKey("trainerId");
                });

            modelBuilder.Entity("EF_1.Model.Course", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EF_1.Model.student", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("EF_1.Model.trainer", b =>
                {
                    b.Navigation("trainers");
                });
#pragma warning restore 612, 618
        }
    }
}
